static xpm_row_t const arrow[] = {
        "12 21 3",
        "  65",
        ". 56",
        "X 63",
/* pixels */
        "..          ",
        "...         ",
        ".X..        ",
        ".XX..       ",
        ".XXX..      ",
        ".XXXX..     ",
        ".XXXXX..    ",
        ".XXXXXX..   ",
        ".XXXXXXX..  ",
        ".XXXXXXXX.. ",
        ".XXXXXXXXX..",
        ".XXXXXX.....",
        ".XXXXXX.    ",
        ".XXXXXX..   ",
        ".X....X .   ",
        "...  .XX..  ",
        "..   ..XX.  ",
        ".     .XX.. ",
        "      ..X . ",
        "       . X. ",
        "       .... "
};
