/* XPM */
static xpm_row_t const nuvem[] = {
/* columns rows colors chars-per-pixel */
"75 42 4",
"  65",
". 0",
"X 7",
"o 63",
/* pixels */

"                       ..........................                          ",
"                       ..........................                          ",
"                       ..........................                          ",
"                       ..........................                          ",
"                 ......oooooooooooooooooooooooooo....                      ",
"                 ......oooooooooooooooooooooooooo....                      ",
"                 ......oooooooooooooooooooooooooo....                      ",
"                 ......oooooooooooooooooooooooooo....                      ",
"      ...........oooooooooooooooooooooooooooooooo....                      ",
"      ...........oooooooooooooooooooooooooooooooo....                      ",
"      ...........oooooooooooooooooooooooooooooooo....                      ",
"      ...........XXXXoooooooooooooooooooooooooooooooo....                  ",
"   ....ooooooooooXXXXoooooooooooooooooooooooooooooooo....                  ",
"   ....ooooooooooXXXXoooooooooooooooooooooooooooooooo....                  ",
"   ....ooooooooooXXXXoooooooooooooooooooooooooooooooo....                  ",
"   ....ooooooooooooooXXXXoooooooooooooooooooooooooXXXXooo............      ",
"....oooooooooooooooooXXXXoooooooooooooooooooooooooXXXXooo............      ",
"....oooooooooooooooooXXXXoooooooooooooooooooooooooXXXXooo............      ",
"....oooooooooooooooooXXXXoooooooooooooooooooooooooXXXXooo............      ",
"....ooooooooooooooooooooooooooooooooooooooooooXXXXoooooooooooooooooo....   ",
"....ooooooooooooooooooooooooooooooooooooooooooXXXXoooooooooooooooooo....   ",
"....ooooooooooooooooooooooooooooooooooooooooooXXXXoooooooooooooooooo....   ",
"....ooooooooooooooooooooooooooooooooooooooooooXXXXoooooooooooooooooo....   ",
"....ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo....",
"....ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo....",
"....ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo....",
"....ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo....",
"....XXXXooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo....",
"....XXXXooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo....",
"....XXXXooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo....",
"....XXXXoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooXXXX....",
"    ....oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooXXXX....",
"    ....oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooXXXX....",
"    ....oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooXXXX....",
"    ....XXXXooooooooooooooooooooooooooooooooooooooooooooooooooooXXXX....   ",
"    ....XXXXooooooooooooooooooooooooooooooooooooooooooooooooooooXXXX....   ",
"    ....XXXXooooooooooooooooooooooooooooooooooooooooooooooooooooXXXX....   ",
"    ....XXXXooooooooooooooooooooooooooooooooooooooooooooooooooooXXXX....   ",
"    ................................................................       ",
"        ............................................................       ",
"        ............................................................       ",
"        ............................................................       ",
};
